### ISSUE TITLE
Fix long gene names

### ISSUE THREAD

**Issue by bruab** [genomeannotation/transvestigator#16]
We have

    gene            1..1533

    /gene="ORF%20c14136_g1_i1%7Cg.5109%20c14136_g1_i1%7Cm.5109
                      %20type%3Acomplete%20len%3A406%20(%2B)"
                      /locus_tag="c14136_g1_i1|g.5109"

We need

    gene="looks_like_a_gene_name_dammit"

**Comment by BrianReallyMany** [comment]
What we want:
* If annotations file provided, ignore any "Name=..." info from GFF
* If no annotations file provided, keep "Name=..." info

**Comment by bdhhtb** [comment]
for now just removing long names; we'll see how it goes. I'm closing this b/c it's so old. If we've still got gene name problems we should just tackle them fresh.
